/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lojademaquiagem;

import javax.swing.JOptionPane;

/**
 *
 * @author ALUNO
 */
public class ClienteTela extends javax.swing.JFrame {

    /**
     * Creates new form ClienteTela
     */
    public ClienteTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomeTXT = new javax.swing.JLabel();
        nomeTXT = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cpfTXT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        telefoneTXT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emailTXT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        endereçoTXT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cidadeTXT = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NomeTXT.setText("Nome:");

        nomeTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTXTActionPerformed(evt);
            }
        });

        jButton1.setText("Criar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("CPF:");

        cpfTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfTXTActionPerformed(evt);
            }
        });

        jLabel2.setText("Telefone:");

        jLabel3.setText("Email:");

        jLabel4.setText("Endereço:");

        jLabel5.setText("Cidade:");

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Atualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NomeTXT)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nomeTXT)
                        .addComponent(cpfTXT)
                        .addComponent(telefoneTXT)
                        .addComponent(emailTXT)
                        .addComponent(endereçoTXT)
                        .addComponent(cidadeTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeTXT))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cpfTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(telefoneTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(emailTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(endereçoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cidadeTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTXTActionPerformed

    private void cpfTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfTXTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (nomeTXT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O Campo Nome esta Vazio!!");
        } else if (cpfTXT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O Campo CPF esta Vazio!!");
        } else if (telefoneTXT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O Campo Telefone esta Vazio!!");
        } else if (emailTXT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O Campo Email esta Vazio!!");
        } else if (endereçoTXT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O Campo Endereço esta Vazio!!");
        } else if (cidadeTXT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O Campo Cidade esta Vazio!!");
        } else {
            
            Cliente cli = new Cliente(
                    nomeTXT.getText(),
                    cpfTXT.getText(),
                    Integer.parseInt(telefoneTXT.getText()),
                    emailTXT.getText(),
                    endereçoTXT.getText(),
                    cidadeTXT.getText());
            
            new ClientDAO().create(cli);
            
            nomeTXT.setText("");
            cpfTXT.setText("");
            telefoneTXT.setText("");
            emailTXT.setText("");
            endereçoTXT.setText("");
            cidadeTXT.setText("");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (nomeTXT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O Campo Nome esta Vazio!!");
        } else if (cpfTXT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O Campo CPF esta Vazio!!");
        } else if (telefoneTXT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O Campo Telefone esta Vazio!!");
        } else if (emailTXT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O Campo Email esta Vazio!!");
        } else if (endereçoTXT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O Campo Endereço esta Vazio!!");
        } else if (cidadeTXT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O Campo Cidade esta Vazio!!");
        } else {
            
            Cliente cli = new Cliente(
                    nomeTXT.getText(),
                    cpfTXT.getText(),
                    Integer.parseInt(telefoneTXT.getText()),
                    emailTXT.getText(),
                    endereçoTXT.getText(),
                    cidadeTXT.getText());
            
            new ClientDAO().update(cli);
            
            nomeTXT.setText("");
            cpfTXT.setText("");
            telefoneTXT.setText("");
            emailTXT.setText("");
            endereçoTXT.setText("");
            cidadeTXT.setText("");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NomeTXT;
    private javax.swing.JTextField cidadeTXT;
    private javax.swing.JTextField cpfTXT;
    private javax.swing.JTextField emailTXT;
    private javax.swing.JTextField endereçoTXT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nomeTXT;
    private javax.swing.JTextField telefoneTXT;
    // End of variables declaration//GEN-END:variables
}
